name: CI-On-Dispatch

on: repository_dispatch

jobs:

  bump_dragonfly_energy:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'dragonfly_energy_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(dragonfly-energy==).*/dragonfly-energy=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump dragonfly-energy to $VERSION"
        git push

  bump_dragonfly_radiance:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'dragonfly_radiance_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(dragonfly-radiance==).*/dragonfly-radiance=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump dragonfly-radiance to $VERSION"
        git push

  bump_dragonfly_uwg:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'dragonfly_uwg_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(dragonfly-uwg==).*/dragonfly-uwg=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump dragonfly-uwg to $VERSION"
        git push

  bump_dragonfly_doe2:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'dragonfly_doe2_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(dragonfly-doe2==).*/dragonfly-doe2=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump dragonfly-doe2 to $VERSION"
        git push

  bump_lbt_honeybee:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'lbt_honeybee_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(lbt-honeybee==).*/lbt-honeybee=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump lbt-honeybee to $VERSION"
        git push
